Stat svc
ValyGer/java-explore-with-me pull request #2
Opened 2024-07-02 00:40 UTC by ValyGer

Сервер сбора статистики

2024-07-02 07:32 UTC, andrew-larkin requested changes
Привет! Структура нового проекта выполнена корректно, но мне кажется, ты не ознакомился со спецификацией в ТЗ. У тебя совсем другие название классов, dto, есть Application. В общем, попробуй исправить в соответствии со спецификацией.

2024-07-02 07:32 UTC, andrew-larkin commented on ewm-service/src/main/resources/aplication.properties
> +logging.level.org.springframework.web.client.RestTemplate=DEBUG
название файла должно быть application.properties

2024-07-02 07:32 UTC, andrew-larkin commented on stats/stats-client/src/main/resources/aplication.properties
> +server.port=8080
везде должно быть application.properties. или application.yml

2024-07-02 07:32 UTC, andrew-larkin commented on stats/stats-dto/src/main/java/ru/practicum/stats/HitDto.java
> +public class HitDto {
можно назвать EndpointHit

2024-07-02 07:32 UTC, andrew-larkin commented on stats/stats-dto/src/main/java/ru/practicum/stats/ApplicationDtoForHitsInt.java
> +public class ApplicationDtoForHitsInt {
это ViewStats

2024-07-02 07:32 UTC, andrew-larkin commented on stats/stats-service/src/main/java/ru/practicum/stats/model/Application.java
> +public class Application {
явно лишний элемент

2024-07-03 22:32 UTC, ValyGer commented on ewm-service/src/main/resources/aplication.properties
> +logging.level.org.springframework.web.client.RestTemplate=DEBUG
Откорректировал, переименовал

2024-07-03 22:32 UTC, ValyGer commented on stats/stats-client/src/main/resources/aplication.properties
> +server.port=8080
Откорректировал, переименовал

2024-07-03 22:33 UTC, ValyGer commented on stats/stats-dto/src/main/java/ru/practicum/stats/HitDto.java
> +public class HitDto {
Откорректировал, переименовал в соответствии со спецификацией

2024-07-03 22:33 UTC, ValyGer commented on stats/stats-dto/src/main/java/ru/practicum/stats/ApplicationDtoForHitsInt.java
> +public class ApplicationDtoForHitsInt {
Откорректировал, переименовал в соответствии со спецификацией

2024-07-03 22:37 UTC, ValyGer commented on stats/stats-service/src/main/java/ru/practicum/stats/model/Application.java
> +public class Application {
Удалил класс сущности Application и связанные dto, сервисы, мапперы, репозиторий. Откорректировал структуру базы данных.  
Соглашусь было сделано криво, получилось убрать половину классов, спасибо за комментарий!

2024-07-05 01:22 UTC, merged